FROM node
LABEL author=archana
LABEL organization=qt
RUN git clone https://github.com/expressjs/express && \
    cd express && \
    npm install express && \
    npm install -g express-generator@4 && \
    express /tmp/foo && \
    cd /tmp/foo && npm install
EXPOSE 3000
WORKDIR /tmp/foo
CMD ["npm","start"]
